### ISSUE TITLE
Probably a dead project, but I want Cerberus X support anyway

### ISSUE THREAD

**Issue by darkhog** [engor/Jentos.Code#41]
If you still care about Monkey X, could you add support for Cerberus X, Monkey X's fork under active development? There's no such feature-full IDE that's free (even as-in-beer kind of free) for Monkey/Cerberus and I'm sick of wrestling with Ted.

**Comment by engor** [comment]
Need to study what the difference between Mx and Cerberus.
If dif is not big enough - I can try. :)

**Comment by darkhog** [comment]
Just download Cerberus and look at Ted sources there. I think the main difference is about calling Cerberus' compiler and support for cxs file extension (used instead of monkey).

**Comment by engor** [comment]
Ok, I pushed commit with supporting of Cerberus-X.
Try it out. :)
